/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_sai.h"
#include "fsl_clock.h"
#include "fsl_gpio.h"
#include "fsl_lpuart.h"
#include "fsl_lpi2c.h"
#include "fsl_pit.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define SAI_1_PERIPHERAL SAI1
/* SAI_1 interrupt vector ID (number). */
#define SAI_1_IRQN SAI1_IRQn
/* SAI_1 interrupt vector priority. */
#define SAI_1_IRQ_PRIORITY 1
/* SAI_1 interrupt handler identifier. */
#define SAI_1_IRQHANDLER SAI1_IRQHandler
/* Bit clock source frequency used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define SAI_1_TX_BCLK_SOURCE_CLOCK_HZ 24000000UL
/* Bit clock source frequency used for calculating the bit clock divider in the RxSetBitClockRate function. */
#define SAI_1_RX_BCLK_SOURCE_CLOCK_HZ 24000000UL
/* Sample rate used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define SAI_1_TX_SAMPLE_RATE 48000UL
/* Sample rate used for calculating the bit clock divider in the RxSetBitClockRate function. */
#define SAI_1_RX_SAMPLE_RATE 48000UL
/* Word width used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define SAI_1_TX_WORD_WIDTH 32U
/* Word width used for calculating the bit clock divider in the RxSetBitClockRate function. */
#define SAI_1_RX_WORD_WIDTH 32U
/* Number of words within frame used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define SAI_1_TX_WORDS_PER_FRAME 2U
/* Number of words within frame used for calculating the bit clock divider in the RxSetBitClockRate function. */
#define SAI_1_RX_WORDS_PER_FRAME 2U
/* Definition of peripheral ID */
#define LPUART_1_PERIPHERAL LPUART1
/* Definition of the clock source frequency */
#define LPUART_1_CLOCK_SOURCE 80000000UL
/* BOARD_InitPeripherals defines for LPI2C1 */
/* Definition of peripheral ID */
#define I2C_PERIPHERAL LPI2C1
/* Definition of clock source */
#define I2C_CLOCK_FREQ 60000000UL
/* Transfer buffer size */
#define I2C_MASTER_BUFFER_SIZE 2
/* BOARD_InitPeripherals defines for PIT */
/* Definition of peripheral ID. */
#define PIT_1_PERIPHERAL PIT
/* Definition of clock source frequency. */
#define PIT_1_CLK_FREQ 62500000UL
/* Definition of ticks count for channel 0. */
#define PIT_1_0_TICKS 249999U
/* PIT_1 interrupt vector ID (number). */
#define PIT_1_IRQN PIT_IRQn
/* PIT_1 interrupt vector priority. */
#define PIT_1_IRQ_PRIORITY 5
/* PIT_1 interrupt handler identifier. */
#define PIT_1_IRQHANDLER PIT_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern sai_transceiver_t SAI_1_Tx_config;
extern sai_transceiver_t SAI_1_Rx_config;
extern const lpuart_config_t LPUART_1_config;
extern const lpi2c_master_config_t I2C_masterConfig;
extern lpi2c_master_transfer_t I2C_masterTransfer;
extern uint8_t I2C_masterBuffer[I2C_MASTER_BUFFER_SIZE];
extern const pit_config_t PIT_1_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
