/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_00 (number 60), USB_OTG1_PWR */
#define BOARD_INITPINS_USB_OTG1_PWR_PERIPHERAL                               USB   /*!< Device name: USB */
#define BOARD_INITPINS_USB_OTG1_PWR_SIGNAL                          usb_otg1_pwr   /*!< USB signal: usb_otg1_pwr */

/* GPIO_12 (number 80), USB_OTG1_OC/U7[A2] */
#define BOARD_INITPINS_USB_OTG1_OC_PERIPHERAL                                USB   /*!< Device name: USB */
#define BOARD_INITPINS_USB_OTG1_OC_SIGNAL                            usb_otg1_oc   /*!< USB signal: usb_otg1_oc */

/* GPIO_13 (number 79), USB_OTG1_ID/J9[4]/Q9[2] */
#define BOARD_INITPINS_USB_OTG1_ID_PERIPHERAL                                USB   /*!< Device name: USB */
#define BOARD_INITPINS_USB_OTG1_ID_SIGNAL                            usb_otg1_id   /*!< USB signal: usb_otg1_id */

/* GPIO_07 (number 5), SAI1_TX_SYNC/U10[13] */
#define BOARD_INITPINS_SAI1_TX_SYNC_PERIPHERAL                              SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_SAI1_TX_SYNC_SIGNAL                           sai_tx_sync   /*!< SAI1 signal: sai_tx_sync */

/* GPIO_06 (number 6), SAI1_TX_BCLK/U10[12] */
#define BOARD_INITPINS_SAI1_TX_BCLK_PERIPHERAL                              SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_SAI1_TX_BCLK_SIGNAL                           sai_tx_bclk   /*!< SAI1 signal: sai_tx_bclk */

/* GPIO_03 (number 10), SAI1_RXD0/U10[16] */
#define BOARD_INITPINS_SAI1_RXD0_PERIPHERAL                                 SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_SAI1_RXD0_SIGNAL                             sai_rx_data0   /*!< SAI1 signal: sai_rx_data0 */

/* GPIO_04 (number 9), SAI1_TXD0/U10[14] */
#define BOARD_INITPINS_SAI1_TXD0_PERIPHERAL                                 SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_SAI1_TXD0_SIGNAL                             sai_tx_data0   /*!< SAI1 signal: sai_tx_data0 */

/* GPIO_08 (number 4), SAI1_MCLK/U10[11] */
#define BOARD_INITPINS_SAI1_MCLK_PERIPHERAL                                 SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_SAI1_MCLK_SIGNAL                                 sai_mclk   /*!< SAI1 signal: sai_mclk */

/* GPIO_02 (number 11), I2C1_SCL/U10[17]/J57[20]/U26[4] */
#define BOARD_INITPINS_I2C1_SCL_PERIPHERAL                                LPI2C1   /*!< Device name: LPI2C1 */
#define BOARD_INITPINS_I2C1_SCL_SIGNAL                                       SCL   /*!< LPI2C1 signal: SCL */

/* GPIO_01 (number 12), I2C1_SDA/U10[18]/J57[18]/U26[6] */
#define BOARD_INITPINS_I2C1_SDA_PERIPHERAL                                LPI2C1   /*!< Device name: LPI2C1 */
#define BOARD_INITPINS_I2C1_SDA_SIGNAL                                       SDA   /*!< LPI2C1 signal: SDA */

/* GPIO_00 (number 13), AUD_INT/U10[15] */
#define BOARD_INITPINS_AUD_INT_PERIPHERAL                                  GPIO1   /*!< Device name: GPIO1 */
#define BOARD_INITPINS_AUD_INT_SIGNAL                                 gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_INITPINS_AUD_INT_CHANNEL                                        0U   /*!< GPIO1 gpiomux_io channel: 00 */

/* GPIO_11 (number 1), USER_LED */
#define BOARD_INITPINS_USER_LED_PERIPHERAL                                 GPIO1   /*!< Device name: GPIO1 */
#define BOARD_INITPINS_USER_LED_SIGNAL                                gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_INITPINS_USER_LED_CHANNEL                                      11U   /*!< GPIO1 gpiomux_io channel: 11 */

/* GPIO_SD_05 (number 70), USER_BUTTON */
#define BOARD_INITPINS_USER_BUTTON_GPIO                                    GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_USER_BUTTON_PORT                                    GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_USER_BUTTON_PIN                                        5U   /*!< GPIO2 pin index: 5 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_09 (number 3), UART1_RXD */
#define BOARD_INITDEBUG_UARTPINS_UART1_RXD_PERIPHERAL                    LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITDEBUG_UARTPINS_UART1_RXD_SIGNAL                            RXD   /*!< LPUART1 signal: RXD */

/* GPIO_10 (number 2), UART1_TXD */
#define BOARD_INITDEBUG_UARTPINS_UART1_TXD_PERIPHERAL                    LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITDEBUG_UARTPINS_UART1_TXD_SIGNAL                            TXD   /*!< LPUART1 signal: TXD */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/* GPIO_SD_10 (number 65), FlexSPI_CLK */
#define BOARD_INITQSPIPINS_FlexSPI_CLK_PERIPHERAL                        FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITQSPIPINS_FlexSPI_CLK_SIGNAL                     FLEXSPI_A_SCLK   /*!< FLEXSPI signal: FLEXSPI_A_SCLK */

/* GPIO_SD_09 (number 66), FlexSPI_D0_A */
#define BOARD_INITQSPIPINS_FlexSPI_D0_A_PERIPHERAL                       FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITQSPIPINS_FlexSPI_D0_A_SIGNAL                   FLEXSPI_A_DATA0   /*!< FLEXSPI signal: FLEXSPI_A_DATA0 */

/* GPIO_SD_07 (number 68), FlexSPI_D1_A */
#define BOARD_INITQSPIPINS_FlexSPI_D1_A_PERIPHERAL                       FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITQSPIPINS_FlexSPI_D1_A_SIGNAL                   FLEXSPI_A_DATA1   /*!< FLEXSPI signal: FLEXSPI_A_DATA1 */

/* GPIO_SD_08 (number 67), FlexSPI_D2_A */
#define BOARD_INITQSPIPINS_FlexSPI_D2_A_PERIPHERAL                       FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITQSPIPINS_FlexSPI_D2_A_SIGNAL                   FLEXSPI_A_DATA2   /*!< FLEXSPI signal: FLEXSPI_A_DATA2 */

/* GPIO_SD_11 (number 64), FlexSPI_D3_A */
#define BOARD_INITQSPIPINS_FlexSPI_D3_A_PERIPHERAL                       FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITQSPIPINS_FlexSPI_D3_A_SIGNAL                   FLEXSPI_A_DATA3   /*!< FLEXSPI signal: FLEXSPI_A_DATA3 */

/* GPIO_SD_06 (number 69), FlexSPI_SS0 */
#define BOARD_INITQSPIPINS_FlexSPI_SS0_PERIPHERAL                        FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITQSPIPINS_FlexSPI_SS0_SIGNAL                    FLEXSPI_A_SS0_B   /*!< FLEXSPI signal: FLEXSPI_A_SS0_B */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitQSPIPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
